import {useEffect, useState, type ReactNode} from 'react';
import {BrowserRouter, NavLink, Route, Routes} from 'react-router-dom';
import {Bell, ChevronDown, Leaf, MapPin, Menu, PackageSearch, ShoppingCart, UserRound, UsersRound, X} from 'lucide-react';

type PublicConfig = {systemName:string;slogan:string;supportEmail:string|null;supportPhone:string|null;defaultCity:string;defaultState:string;currency:string;timezone:string;revision:number};
const fallbackBrand = {systemName:'HortiVitalMix', slogan:'Do produtor local para a sua mesa'};

function Brand({compact=false}:{compact?:boolean}) {
  return <NavLink to="/" className="brand" aria-label="HortiVitalMix - início"><span className={compact?'brand-icon compact':'brand-icon'}><Leaf aria-hidden="true" /></span><span className="brand-copy"><strong><span>Horti</span><em>Vital</em><span>Mix</span></strong>{!compact&&<small>Tudo fresco. Tudo da sua região.</small>}</span></NavLink>;
}
const navigation=[['/','Início'],['/produtores','Produtores'],['/produtos','Produtos'],['/planos','Planos'],['/sobre','Sobre nós']] as const;

function DesktopHeader({location}:{location:string}) {
  const [open,setOpen]=useState(false);
  return <header className="desktop-header"><div className="header-inner"><Brand/><nav aria-label="Navegação principal">{navigation.map(([to,label])=><NavLink key={to} to={to} end={to==='/' }>{label}</NavLink>)}</nav><div className="header-actions"><button className="location-button" type="button"><MapPin/><span>{location}</span><ChevronDown/></button><button className="icon-button" aria-label="Notificações" type="button"><Bell/></button><button className="icon-button" aria-label="Carrinho" type="button"><ShoppingCart/></button><NavLink className="login-button" to="/entrar">Entrar</NavLink><div className="signup-wrap"><button className="signup-button" onClick={()=>setOpen(!open)} aria-expanded={open}>Cadastre-se <ChevronDown/></button>{open&&<div className="signup-menu"><NavLink to="/cadastro/consumidor">Sou consumidor</NavLink><NavLink to="/cadastro/produtor">Sou produtor</NavLink></div>}</div></div></div></header>;
}

function MobileHeader({location}:{location:string}) {
  const [open,setOpen]=useState(false);
  return <header className="mobile-header"><div className="mobile-top"><Brand compact/><button className="mobile-location" type="button"><MapPin/>{location}<ChevronDown/></button><button className="icon-button" aria-label="Abrir menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div>{open&&<nav className="mobile-menu" aria-label="Menu complementar"><NavLink to="/sobre" onClick={()=>setOpen(false)}>Sobre nós</NavLink><NavLink to="/entrar" onClick={()=>setOpen(false)}>Entrar</NavLink><NavLink to="/cadastro/consumidor" onClick={()=>setOpen(false)}>Cadastro consumidor</NavLink><NavLink to="/cadastro/produtor" onClick={()=>setOpen(false)}>Cadastro produtor</NavLink></nav>}</header>;
}

function BottomNav(){const items=[['/','Início',Leaf],['/produtores','Produtores',UsersRound],['/produtos','Produtos',PackageSearch],['/planos','Planos',ShoppingCart],['/entrar','Conta',UserRound]] as const;return <nav className="bottom-nav" aria-label="Navegação móvel">{items.map(([to,label,Icon])=><NavLink key={to} to={to} end={to==='/' }><Icon/><span>{label}</span></NavLink>)}</nav>}

function Home({config,status,retry}:{config:PublicConfig|null;status:'loading'|'ready'|'error';retry:()=>void}){const brand=config??fallbackBrand;return <main className="home-page">{status==='loading'&&<div className="system-state" role="status">Carregando configuração segura do sistema…</div>}{status==='error'&&<div className="system-state error" role="alert"><div><strong>Serviço temporariamente indisponível</strong><span>Não foi possível confirmar a configuração no servidor.</span></div><button onClick={retry}>Tentar novamente</button></div>}<section className="hero"><div className="hero-copy"><span className="eyebrow">DO CAMPO PARA A CIDADE</span><h1>Produtos frescos da nossa região, direto para você.</h1><p>{brand.slogan}. Conectamos famílias a produtores locais com praticidade e transparência.</p><div className="hero-actions"><NavLink to="/produtos" className="primary-cta">Conhecer produtos</NavLink><NavLink to="/produtores" className="secondary-cta">Ver produtores</NavLink></div><div className="benefits"><span><Leaf/> Produtos frescos</span><span><UsersRound/> Direto do produtor</span><span><MapPin/> Entrega regional</span></div></div><div className="hero-visual" aria-label="Ilustração de folhas frescas"><div className="leaf-orbit"><Leaf/><Leaf/><Leaf/></div><div className="hero-seal"><strong>{config?`${config.defaultCity} - ${config.defaultState}`:'Localização'}</strong><span>Origem regional</span></div></div></section><section className="empty-showcase" aria-labelledby="showcase-title"><div><span className="eyebrow">VITRINE REGIONAL</span><h2 id="showcase-title">A seleção começa com produtores verificados</h2><p>Os produtos serão exibidos aqui somente quando estiverem cadastrados e publicados no servidor.</p></div><NavLink to="/produtos">Explorar catálogo</NavLink></section></main>}

function PendingPage({title,description,icon}:{title:string;description:string;icon:ReactNode}){return <main className="content-page"><div className="content-icon">{icon}</div><span className="eyebrow">HORTIVITALMIX</span><h1>{title}</h1><p>{description}</p><NavLink to="/">Voltar ao início</NavLink></main>}
function Footer({config}:{config:PublicConfig|null}){return <footer><div><Brand/><p>Valorizamos quem produz. Facilitamos para quem consome.</p></div><div><strong>Região inicial</strong><span>{config?`${config.defaultCity} - ${config.defaultState}`:'Ariquemes - RO'}</span><span>{config?.supportEmail??'Atendimento será disponibilizado em breve'}</span></div></footer>}

function Shell(){const[config,setConfig]=useState<PublicConfig|null>(null);const[status,setStatus]=useState<'loading'|'ready'|'error'>('loading');const load=async()=>{setStatus('loading');try{const response=await fetch('/api/v1/config',{headers:{accept:'application/json'}});if(!response.ok)throw new Error('CONFIG_UNAVAILABLE');const payload=await response.json() as {data:PublicConfig};setConfig(payload.data);setStatus('ready')}catch{setStatus('error')}};useEffect(()=>{void load()},[]);const location=config?`${config.defaultCity} - ${config.defaultState}`:'Selecionar localização';return <div className="app-shell"><DesktopHeader location={location}/><MobileHeader location={location}/><Routes><Route path="/" element={<Home config={config} status={status} retry={()=>void load()}/>}/><Route path="/produtores" element={<PendingPage title="Produtores locais" description="A listagem será liberada quando os primeiros produtores forem verificados. Nenhum dado fictício é apresentado." icon={<UsersRound/>}/>}/><Route path="/produtos" element={<PendingPage title="Produtos frescos" description="O catálogo exibirá somente itens reais publicados por produtores autorizados." icon={<PackageSearch/>}/>}/><Route path="/planos" element={<PendingPage title="Planos HortiVitalMix" description="Os planos serão apresentados quando preços e condições estiverem confirmados no servidor." icon={<ShoppingCart/>}/>}/><Route path="/sobre" element={<PendingPage title="Do produtor local para a sua mesa" description="O HortiVitalMix conecta produtores do Vale do Jamari a consumidores que valorizam frescor, origem e praticidade." icon={<Leaf/>}/>}/><Route path="/entrar" element={<PendingPage title="Acesso à conta" description="A autenticação segura será ativada na próxima trilha, com portais separados por perfil." icon={<UserRound/>}/>}/><Route path="/cadastro/consumidor" element={<PendingPage title="Cadastro de consumidor" description="Esta jornada será ativada junto da identidade e validação server-side da próxima trilha." icon={<UserRound/>}/>}/><Route path="/cadastro/produtor" element={<PendingPage title="Cadastro de produtor" description="Esta jornada terá portal próprio e validação rural, sem mistura com contas de consumidor." icon={<UsersRound/>}/>}/><Route path="*" element={<PendingPage title="Página não encontrada" description="O endereço informado não existe." icon={<PackageSearch/>}/>}/></Routes><Footer config={config}/><BottomNav/></div>}
export default function App(){return <BrowserRouter><Shell/></BrowserRouter>}
